### ISSUE TITLE
How to Create Node like Decision

### ISSUE THREAD

**Issue by mike-hor** [awslabs/diagram-maker#20]
First of all, thank you very much for this library

Now I have integrated the library into my app, but I don't know how to create multi branch nodes.
It's like this:
![image](https://user-images.githubusercontent.com/17822235/96133415-81c44280-0f2d-11eb-8b31-71cb66f13dbf.png)

![image](https://user-images.githubusercontent.com/17822235/96134771-f0090500-0f2d-11eb-9dc4-cd227c0a6bb1.png)

**Comment by sameergoyal** [comment]
Thanks for using this library.

Diagram Maker doesn't provide an inbuilt choice node, however one could be rendered via various different approaches. Choosing the right approach will depend on your use case and desired user experience and behavior.

### Approach 1 (Using edges with different connector placements)
With Diagram Maker, you could either get connectors pre-rendered by Diagram Maker using either the [LeftRight](https://awslabs.github.io/diagram-maker/usage/configuration.html#connector-placement) or [TopBottom](https://awslabs.github.io/diagram-maker/usage/configuration.html#connector-placement) connector placement. With such connector placements a choice node could look like this:
<img width="396" alt="Screen Shot 2020-10-19 at 4 15 38 AM" src="https://user-images.githubusercontent.com/1594391/96444169-a4bb5480-11c2-11eb-87b7-463d68913afa.png">
<img width="449" alt="Screen Shot 2020-10-19 at 4 15 43 AM" src="https://user-images.githubusercontent.com/1594391/96444156-9ec57380-11c2-11eb-9c36-b51c8168fcc9.png">

The other way could be to not have Diagram Maker render connectors and use a [Centered](https://awslabs.github.io/diagram-maker/usage/configuration.html#connector-placement) or [Boundary](https://awslabs.github.io/diagram-maker/usage/configuration.html#connector-placement) connector placements. The choice node in that case could look like this:
<img width="515" alt="Screen Shot 2020-10-19 at 4 15 34 AM" src="https://user-images.githubusercontent.com/1594391/96443869-2c549380-11c2-11eb-8d6d-6e89f465d778.png">
Note that this above example also uses edge badges which could be used with the Left Right & Top Bottom connector placements as well.

The code for these examples is present here for your reference: https://github.com/sameergoyal/diagram-maker/tree/choice-node-demo.

### Approach 2 (Using "mini" nodes that represent choices)
Another approach could be using "mini" nodes to represent fixed choices. When a new choice node is dropped, you could use [action interceptor](https://awslabs.github.io/diagram-maker/usage/configuration.html#action-interceptor) to also drop 2 more nodes of a certain [node type](https://awslabs.github.io/diagram-maker/usage/configuration.html#node-type-configuration). You can then use action interceptor to make the 3 nodes (choice and 2 options) move as a group if you wished so. One of the consumers of the library [AWS IoT Things Graph](https://console.aws.amazon.com/thingsgraph/home?region=us-east-1#/flows/create) implemented the notion of a choice node with a variation of this approach. This is how a sample choice node looks like on their console:
<img width="1016" alt="Screen Shot 2020-10-19 at 4 37 30 AM" src="https://user-images.githubusercontent.com/1594391/96445921-8571f680-11c5-11eb-85b0-d6a2f6413d3d.png">

Let us know if one of the above outlined approach works for you. If not, it will be great if you could describe your use case & intended user experience in more detail so we could better suggest a solution or use it to build a feature enhancement request.

**Comment by mike-hor** [comment]
Thank you for your reply. I used approach 1
![image](https://user-images.githubusercontent.com/17822235/96596711-9898d980-131f-11eb-9b52-ac318d9da337.png)
