### ISSUE TITLE
Styling of edges

### ISSUE THREAD

**Issue by coreteam-co** [awslabs/diagram-maker#28]
Thanks for this library. Is there a possibility to style edges using CSS classes? In case of nodes I can easily add a CSS class as part of the `renderCallback`. But I cannot find a way to do the same for edges. Is this possible or could this be a feature implemented in the library?

**Comment by sameergoyal** [comment]
We use a set of stable CSS classes on the edges inside Diagram Maker that can be used to apply CSS overrides on the edges either globally or using edgeID. 

```
<containerDivId or containerDivClass> .dm-edge .dm-path.dm-path-inner {
    stroke-dasharray: 4;
    stroke: black;
}
```

The container div is added to the CSS rule to ensure the rule added by you has higher specificity than the CSS within the library itself. It is also possible to update specific edges only using the edgeId like so:

```
<containerDivId or containerDivClass> .dm-edge[data-id="edgeId"] .dm-path.dm-path-inner {
    stroke-dasharray: 4;
    stroke: black;
}
```


We recently added a feature in version 1.1.0 to allow overriding CSS on edges based on source/destination node type. See more details here: https://github.com/awslabs/diagram-maker/issues/16.

**Comment by coreteam-co** [comment]
Cool stuff, thanks a lot for your fast feedback. It works as expected.
