### ISSUE TITLE
Preact Examples

### ISSUE THREAD

**Issue by arbs-io** [awslabs/diagram-maker#31]
This is a fantastic project. I'm struggling with migrating a simple example to a preact application. I would really appreciate an example (like the vanilla js) in preact. Is this something you're considering to include? It would really help with the adoption of the library.

Many thanks

**Comment by sameergoyal** [comment]
We have some preact examples over here: https://awslabs.github.io/diagram-maker/usage/configuration.html. 
<img width="1055" alt="Screen Shot 2021-02-01 at 11 53 44 AM" src="https://user-images.githubusercontent.com/1594391/106510935-6e10fd80-6484-11eb-891d-23490830816c.png">

Can you check and let us know if this is what you wanted? In case you were looking for something else, can you describe the parts where you would like to see more documentation?

**Comment by arbs-io** [comment]
Many thanks for swift response. I did see the snippet for nodes. Do you have something similar for the container. Would you suggest making our own wrapper lib for react/preact? diagram-maker-react

I was just wondering if this was on your roadmap or not.

Like the sample vanilla ha example having other framework variations to be very helpful.

**Comment by sameergoyal** [comment]
We have updated the docs with an example of how to consume this library within preact/react.

**Comment by arbs-io** [comment]
Perfect! Many thanks and such a quick turnaround. Very much appreciated. Awesome project!!!
