### ISSUE TITLE
Dark theme missing from NPM package

### ISSUE THREAD

**Issue by JohnCyberWick** [awslabs/diagram-maker#55]
Hello,

I'm trying to use the dark theme as explained in the documentation. Unfortunately, I can't make it work. It seems that the feature is missing from the NPM package 1.2.0 or not fully documented.

**To Reproduce**
1. Install the NPM package
2. Follow the documentation (add class on body)
3. Nothing happens

**Expected behavior**
The dark theme is applied.

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Firefox 78 ESR

PS: examples from the NPM package are differents (olders ?) than the ones displayed on github.

Best regards

**Comment by sameergoyal** [comment]
Apologies for the late response. You can see a documentation for how to enable dark mode here: https://awslabs.github.io/diagram-maker/usage/initialization.html#dark-theme.

Essentially it involves adding a class on the container in which Diagram Maker is rendered: 
```
<div id="diagramMakerContainer" class="dm-dark-theme">
```

You can also see a live demo of the dark mode here: https://awslabs.github.io/diagram-maker/examples/DarkTheme.html.

Let us know if you run into further issues while using the dark mode.

**Comment by JohnCyberWick** [comment]
No problem, thanks for your response.

Updating the package from 1.2.0 to 1.3.0 fixed it. Should I close the issue or are you willing to look further into this?

**Comment by sameergoyal** [comment]
I think we can go ahead & close this issue. We anyways recommend using the latest version whenever no breaking changes are introduced and we only do minor version upgrades..
