### ISSUE TITLE
Drag multiple nodes

### ISSUE THREAD

**Issue by JohnCyberWick** [awslabs/diagram-maker#56]
Hello,

The library allows to select multiple nodes at the same time. It would be great if you could also move them all together.

**Describe the solution you'd like**
Use the selection marquee tool to select multiple nodes.
Click and drag one of them.
The others follow while keeping their relative position to each others.

**Describe alternatives you've considered**
Should it be a plugin or a core feature ?

Best regards

**Comment by sameergoyal** [comment]
Apologies for the delay in our response.

I think this could be a core feature and it is a good suggestion for enhancement. Would you be willing to submit a PR for this?

**Comment by JohnCyberWick** [comment]
Thanks for your response,

I'm willing to submit a PR but I still can't give you a clear estimate right now. I'm going to take a look on this one after #53.

**Comment by sameergoyal** [comment]
Thanks for contributing back.

Let us know if you need additional guidance on how to implement this change.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
