### ISSUE TITLE
Copy/paste nodes and edges

### ISSUE THREAD

**Issue by JohnCyberWick** [awslabs/diagram-maker#57]
Hello,

I often find myself making similar diagrams (or at least having some patterns coming back quite frequently).
Instinctively I want to copy/paste my work.

**Describe the solution you'd like**
I think the best or more intuitive solution would be : 
1. Select mutliple nodes and edges
2. Hit ctrl + c
3. Hit ctrl + v
4. The selected nodes and edges are added to your canvas/workspace while keeping their states/connections/relative positions to each others

Best regards

**Comment by sameergoyal** [comment]
Apologies for the delay in our response.

It is a good suggestion for enhancement. Would you be willing to submit a PR for this?

**Comment by JohnCyberWick** [comment]
Thanks for your response,

I'm willing to submit a PR but I can't give you a clear estimate on this one. I might be able to work on it by the end of Q3 depending on my free time.

**Comment by sameergoyal** [comment]
Thanks for contributing back.

Let us know if you need additional guidance on how to implement this change.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
