### ISSUE TITLE
Auto align

### ISSUE THREAD

**Issue by JohnCyberWick** [awslabs/diagram-maker#58]
Hello,

When I make a diagram, I would like to be able to auto align every nodes. A misalignment in a diagram is not very important but people that see my diagram often make comments about it.

**Describe the solution you'd like**
When you move a node, it snap to an imaginary/invisible strait line going through  the middle of the closest node.
The line could also be visible.

Best regards

**Comment by sameergoyal** [comment]
Apologies for the delay in our response.

It is a good suggestion for enhancement. Would you be willing to submit a PR for this?

The change would require checking during node moves, the positions of other nodes and see if this node aligns horizontally or vertically with other nodes and if it is within a pre-defined range of being aligned, snap to that position. One thing to keep in mind for this change would be the performance impact of this change when there are larger number of nodes on the canvas. Maybe, we might need to perform some additional performance testing before we will be able to pull in this change.

**Comment by JohnCyberWick** [comment]
Thanks for your response,

I'm willing to submit a PR but I can't give you a clear estimate on this one. I might be able to work on it by the end of Q3 depending on my free time.

**Comment by sameergoyal** [comment]
Thanks for contributing back.

Let us know if you need additional guidance on how to implement this change.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
