### ISSUE TITLE
Document Browser Support

### ISSUE THREAD

**Issue by jtl3d** [awslabs/diagram-maker#65]
**Describe the issue with documentation**
I cannot find any mention of supported browsers in the documentation. I apologize if I just missed it, but in that case it should probably be more prominent.

I noticed that the demos don't function properly in ie11, and that ie11 also causes errors in the AWS IoT Things Graph Console. Is ie11 supported via polyfill?

Thanks!

**Comment by occhangg** [comment]
Thank you for point this out. 

We can add a list of supported blowers section as soon as we are done with other higher priority items.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
