### ISSUE TITLE
Error when React component is unmounted

### ISSUE THREAD

**Issue by mawaruDOLL** [awslabs/diagram-maker#66]
**Describe the bug**
I'm using diagram-maker in a React functional component. When the component is unmounted due to a client side route change, I get a message like the following for every node and panel that is currently displayed in the diagram:

Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

The nodes and panel are also React components rendered by calling ReactDOM.render. These components simply have some props passed in and do not make use of any hooks. Please see the component definition below.

**To Reproduce**
```
function WorkflowDiagram(props:IProps) {
  const container = useRef<HTMLDivElement>(null);
  let diagramMaker:DiagramMaker<IWorkflowNode, IWorkflowEdge>;

  const config:DiagramMakerConfig<IWorkflowNode, IWorkflowEdge> = {
    options: {
      connectorPlacement: ConnectorPlacement.TOP_BOTTOM,
      showArrowhead: true
    },
    renderCallbacks: {
      node: (node: DiagramMakerNode<IWorkflowNode>, diagramContainer: HTMLElement) =>
        ReactDOM.render(<WorkflowNode />, diagramContainer),
      potentialNode: (node: DiagramMakerPotentialNode, diagramContainer: HTMLElement) => {
        ReactDOM.render(<WorkflowNode />, diagramContainer)
      },
      panels: {
        library: (panel: any, state: any, diagramContainer: HTMLElement) => {
          ReactDOM.render(<StepLibraryPanel />, diagramContainer);
        },
      },
      destroy: (cont: HTMLElement) => ReactDOM.unmountComponentAtNode(cont)
    },
  };

  useEffect(() => {
    const initialData:DiagramMakerData<IWorkflowNode, IWorkflowEdge> = {
      nodes,
      edges,
      workspace: {
        position: { x: 0, y: 0 },
        scale: 1,
        canvasSize: { width: 1200, height: 600 },
        viewContainerSize: { width: window.innerWidth, height: window.innerHeight }
      },
      editor: { mode: EditorMode.DRAG },
      panels: {
        library: {
          id: 'library',
          position: { x: 10, y: 10 },
          size: { width: 250, height: 400 },
          positionAnchor: PositionAnchor.TOP_RIGHT
        },
      }
    };

    diagramMaker = new DiagramMaker(
      container.current as HTMLElement,
      config,
      {
        initialData,
      }
    );

    return () => {
      diagramMaker.destroy();
    };
  }, [props.workflow]);

  return <div id="workflowDiagram" ref={container} />;
}
```
The console errors occur when when I am viewing a diagram rendered with a component like this one and the client side route is changed by clicking a link to another page in the application, thus causing the component with the diagram to be unmounted.

**Expected behavior**
I expect that all components should be unmounted without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/15877771/127195854-2e46b6c6-c636-4821-8061-eb034e57aefc.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.164

**Additional context**
React 17
React DOM 17
React Router DOM 5.2
Diagram Maker 1.3

**Comment by NorbertNader** [comment]
@mawaruDOLL  Thank you for bringing up this issue!

We have acknowledged this issue and will look at this as soon as we are done with other higher priority items.

**Comment by occhangg** [comment]
Apologies for the delay in our response.

If you are still facing this bug and are still interested to work with us on this issue, could you please help us reproduce the problem that you are facing in the code sandbox? I have already copy and pasted the code that you have provided into the code sandbox.

https://codesandbox.io/s/competent-shannon-dfce3?file=/src/WorkflowDiagram.tsx

**Comment by mawaruDOLL** [comment]
I made a small app that demonstrates the issue at https://github.com/mawaruDOLL/react-diagram-maker-example. There are 2 links at the top of the page when you start the application. If you click the diagram link and let the page load, then click the home link, you will see errors in the console.

**Comment by occhangg** [comment]
Thanks for setting this up!

Based on what I am seeing right now, it seems like when you go from the diagram tab to the home tab, the diagram dom element no longer exists within the dom tree. 

You can try this out
```
    return () => {
      debugger
      diagramMaker.destroy();
    };
```

and type `document.getElementById('diagram')` into the console and you will get `null`. 

What I can propose is we change up the function a bit and include a guard.
```
    return () => {
      if(container.current != null) {
        diagramMaker.destroy();
      }
    };
```

Here we are checking if the container still exists or not. if it is, we can call `.destroy` function. Otherwise, skip because it does not exist anymore due to top level dom tree being removed or for other reasons. 


Please let us know if you have any other questions.

**Comment by mawaruDOLL** [comment]
Thank you, that helps. I'm noticing in the larger application I'm working on that panning and dragging on the canvas is choppy and stutters if I navigate from an application page with a diagram to another page that doesn't have one, then back to the diagram page. It's fine the first time the diagram loads though, which is one of the reasons I thought .destroy needed to be called. But I'm not seeing the same behavior in the example app I linked above so there must be something else going on in the other application. Thanks again for the help!

**Comment by occhangg** [comment]
No problem. Seem like this issue has been resolve. I believe we can go head and mark this one as close.

**Comment by mawaruDOLL** [comment]
I just found more console errors in the example app but I'm not sure if they're related to the original issue. Follow the same steps of going to the diagram page, navigating to home, then going back to the diagram. The second time you are on the diagram, add a new node and drag an edge out from the new node. This causes exceptions to occur as you move the potential edge around: Cannot read property 'typeId' of undefined. This doesn't happen the first time the diagram is loaded.

**Comment by NorbertNader** [comment]
Seems like this issue is not an issue with diagram-maker but ReactDOM. Please feel free to open a new issue for the bug. Thank you!
