### ISSUE TITLE
Is it possible to add custom number of Connectors for Nodes?

### ISSUE THREAD

**Issue by rahul-codeb** [awslabs/diagram-maker#67]
Hi, I'm finding difficulty to manage custom number of connectors to the nodes. Right now, Diagram-Maker Nodes only support (one input and one output). 

Also, please let us know, if it is possible to create custom-standard nodes in diagram maker.

**Comment by occhangg** [comment]
Apologies for the delay in our response and thank you for reaching out. 

Could you please expand more on your use case?

**Comment by notsonoobiee** [comment]
I want implement custom number to Left-Right-Rectangular Node, and the connector behaviour should be completely configurable (Dropzone / Draggable). 

Expectations : 
![image](https://user-images.githubusercontent.com/89071284/129899719-6b2925c2-4115-41ea-b3bc-70e28c1a3062.png)

Please, let me know if this is possible, and if possible please provide a demo code. 

Thanks.

**Comment by nkev** [comment]
@NorbertNader I don't understand why you would not even plan adding multiple inputs/outputs to nodes. 

It's the most basic functionality and the first thing anyone is going to ask for when building something a little more complex than a single input and output, right?

**Comment by sameergoyal** [comment]
You can add multiple inputs & outputs already by just adding the right data attributes. See the relevant documentation around it: https://awslabs.github.io/diagram-maker/usage/declarative.html#customizing-the-node-connectors.

However, what's currently not possible is for edges to start & end at these "custom" connectors. That feature would need to be added.

**Comment by ktsao565** [comment]
I'm going to try and give this a shot and submit a PR.

**Comment by diehbria** [comment]
@nkev I would like to clarify, there is no plans for the maintainers to actively create this feature, not that we would not accept this feature as a contribution. We would be happy to accept this feature. We are in communications with another user of this library, @tsao565 who is interested in implementing this. Stay tuned :-)

**Comment by nkev** [comment]
Thanks @diehbria but I have since moved on to using [drawflow](https://jerosoler.github.io/Drawflow/), which better suits my needs.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
