### ISSUE TITLE
Documentation on local dev environment setup

### ISSUE THREAD

**Issue by riyazghati** [awslabs/diagram-maker#75]
Could'nt find the documentation for setting up local run time environment for the package.
Even though examples are given under **integ** directory, it uses compiled code to run.
Adding details on how to locally run the source code would allow to run the package locally.

**Comment by richardaum** [comment]
I would be very good to explain how to run the demo code. I've tried to run `npm run start` and then navigate to `http://localhost:31213/ActionInterceptor` but it didn't work. It says:

```
Uncaught Error: Container not found
    at DiagramMaker.getContainer (DiagramMaker.ts:106)
    at new DiagramMaker (DiagramMaker.ts:60)
    at renderDiagramMaker (render.ts:23)
    at Module../integ/ActionInterceptor/index.ts (index.ts:5)
```

**Comment by sameergoyal** [comment]
@riyazghati,

Can you try the steps outlined by @richardaum and see if that works for you?

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
