### ISSUE TITLE
It would be great to have nested functionality

### ISSUE THREAD

**Issue by jackson-daniel** [awslabs/diagram-maker#77]
To contextualize the nodes, it would be great if the nodes can be grouped. Similar to how the Cloud Formation Designer works where you can have a VPC and EC2 instances within it.

**Comment by occhangg** [comment]
Thanks for the suggestion. We will look into this as soon as we can.

**Comment by richardaum** [comment]
I'm also looking for this feature. Dagree D3 calls it a cluster: [demo](https://dagrejs.github.io/project/dagre-d3/latest/demo/clusters.html).

Is there any ideia about how to achieve that here? Maybe we could help to implement it.

**Comment by NorbertNader** [comment]
Hey @richardaum I think that is a great idea, thank you for the suggestion! Please feel free to contribute and we would love to review your PR.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
