### ISSUE TITLE
How do i make diagram-maker only render inside the dom node i am passing and not occupy all screen

### ISSUE THREAD

**Issue by ymolists** [awslabs/diagram-maker#79]
**Describe the issue with documentation**
A clear and concise description of what the issue is.
Right now diagram make is taking all my screen in my react app. I was assuming that it would render inside the HTMLElement that i am passing by default and not take over all my screen real estate.

1) can someone please show me how i would make this work in a create react app ?
2) would you consider making it the default behaviour ?
3) can someone please point me to any react application out there using diagram maker ?

**Comment by diehbria** [comment]
Hi,  you can customize the styling the styling by targeting the css selectors used within, for example 


```
.dm-canvas {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
  user-select: none;
}
```

I think the default behavior you mention makes sense, and we would definitely consider making it the default behavior
