### ISSUE TITLE
Trigger an action when hovering edges

### ISSUE THREAD

**Issue by richardaum** [awslabs/diagram-maker#84]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When I hover an edge, I'd like to highligh its `src` and `dest` node.

**Describe alternatives you've considered**
Right now, I'm using `renderCallbacks.edge` to add event listeners on `.dm-edge` all elements. When a edge is hovered (mouse-enter and mouse-leave), I search on DOM for element which `data-id = src` and `data-id = dest`. Is that the best option? 

I've also tried to use actionInterceptor and eventListener but it seems like there is nothing about hover actions. What about introducing them as a kind of interaction (not only clicking).

**Additional context**
N/A

**Comment by NorbertNader** [comment]
Thank you for creating this issue. We will take a look at this issue and get back to you as soon as possible.

**Comment by NorbertNader** [comment]
Apologies for the late response. I think your solution is the right way to go for your use case. However, if you would be open to contribute a hover action to the existing [edge actions](https://github.com/awslabs/diagram-maker/blob/master/src/state/edge/edgeActions.ts) we would love to review your solution. I think others might benefit from this as well. Please feel free to open a PR.

Thank you!

**Comment by richardaum** [comment]
Let me try it as my first contribution! 

Btw, this is the best library I've found around and you guys are very kind and responsive. Thanks a lot! 🎉
