### ISSUE TITLE
[Vue warn]: Error in beforeDestroy hook: "TypeError: _this.props.destroyCallback is not a function"

### ISSUE THREAD

**Issue by thedevyounotexpect** [awslabs/diagram-maker#88]
I have an DiagramMaker running in VueJs component and I'm trying to destroy it in one of the lifecycle hooks. While the call to destroy happens I get this error. It happens every time the destroy is called.

`
beforeDestroy () {
    this.diagram.destroy()
}
`

**Comment by NorbertNader** [comment]
Closing since there has not been any response. Please feel free to reopen with reproduction steps. Thank you!
