### ISSUE TITLE
Un-minify example code 

### ISSUE THREAD

**Issue by saminzadeh** [awslabs/diagram-maker#9]
This project looks promising but the [examples directory](https://github.com/awslabs/diagram-maker/tree/master/docs/examples) contains code that has already been [minified](https://github.com/awslabs/diagram-maker/blob/master/docs/examples/Layout.js) which makes it difficult to learn by example. Is it possible to check in the original source code?

**Comment by sameergoyal** [comment]
Ths unminified code is already checked in here: https://github.com/awslabs/diagram-maker/tree/master/integ. The way we have set up our documentation & demo website, we have to check in the generated code as well.

**Comment by saminzadeh** [comment]
Ah, great - it was hard to find at first. Thanks for adding the links to the readme!
